### ISSUE TITLE
nx generate @joelcode/gcp-function:http fails

### ISSUE THREAD

**Issue by prmichaelsen** [JoelCode/gcp-function#8]
I followed the setup instructions:
* running node v13.12.0
* ran gcloud auth
* installed requisite packages via npm

However when generating a function I receive this error: `Cannot read property 'Application' of undefined`

I searched the code for `Application` but do not see where it may be occurring.

Example:
```
nx generate @joelcode/gcp-function:http publish                      
? What function prefix would you like to you? dev
? Which runtime would you like to use? nodejs13
? What's the maximal quantity of instances? 10
? Where should the function be hosted? us-central1
Cannot read property 'Application' of undefined
```

**Comment by JoelCode** [comment]
Name your module something else than "publish" or any reserved word.

**Comment by JoelCode** [comment]
I can't reproduce this error, maybe you changed some to the NX file name or something like that.

**Comment by prmichaelsen** [comment]
recreating workspace from scratch fixes the issue. 

problem was my workspace was initially configured with `angular` yielding an `angular.json` instead of `workspace.json`.
```
❯ angular           [a workspace with a single Angular application] 
  nest              [a workspace with a single Nest application] 
```
